### ISSUE TITLE
[META] CI Sprint Barcelona

### ISSUE THREAD

**Issue by podarok** [propeoplemd/cibox#280]
We've decided to work on CI and make some fixes and refactorings.

* [ ] Split the project to small ones into https://github.com/CIBox infrastructure
  * [ ] Virtual machine (merge with http://dgo.to/vdd afterwards) https://github.com/CIBox/cibox-vm
  * [ ] CI server provisioning https://github.com/CIBox/cibox-server-provisioning
  * [ ] Project builder https://github.com/CIBox/cibox-project-builder
* [ ] Refactor VM with putting all CI scripts into devops only subfolder
* [ ] #210 Add varnish for CI server and Vagrantbox
* [ ] Make all roles shippable for ansible-galaxy and put them their
* [ ] Add jenkins provisioning playbook testing for CI-CI
