### ISSUE TITLE
[META] Capture GitHub credentials and project URL in config file

### ISSUE THREAD

**Issue by Sanchiz** [propeoplemd/cibox#299]
We should capture this data in some config file to avoid manual steps.

Here's only one issue that is related to "Credentials" plugin.
http://xn--thibaud-dya.fr/jenkins_credentials.html
Probably we should create custom Jenkins plugin in order to encrypt password and put into `credentials.xml`.

- [x] #328 GitHub URL in config file
- [x] #329 GitHub bot credentials(GitHub plugin config) in config file
- [ ] #330 GitHub bot credentials(user config) in config file

**Comment by podarok** [comment]
@Sanchiz http://www.philipp.haussleiter.de/2011/11/jenkins-password-hash-format/

**Comment by podarok** [comment]
We can provide a custom bash/php/script based password creation by ansible itself without creating jenkins plugin

**Comment by Sanchiz** [comment]
Cool, thanks @podarok !

**Comment by Sanchiz** [comment]
@podarok this is related to users password, but I was talking about `/var/lib/jenkins/credentials.xml` there being used another algorithm.
